config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root 'home#index'

  resources:products 

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ApplicationRecord
  validates :product_name, uniqueness: { case_sensitive: false }
  validates_length_of :product_name, minimum: 5, maximum: 10
   validates :product_name, :description, :price, presence: true
  belongs_to :user


end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many:products
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
  class ApplicationController < ActionController::Base




    before_action :configure_permitted_parameters, if: :devise_controller?

    protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index

  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products=current_user.products

  end

  def show
  end

  def new
    @product=Product.new
  end

  def create

    @product=Product.new(set_params)
    @product.user_id=current_user.id
    if @product.save
      flash[:notice]="Product created successfully !"
      redirect_to root_path
    else
    render :new
    end
  end

  def edit
    @product=Product.find(params[:id])

  end

  def update

      @product=Product.find(params[:id])

      if @product.update(set_params)
        flash[:notice]="Product updated successfully"
        redirect_to products_path
      else
        flash[:alert]="Product didn't update successfully !!!"
        redirect_to edit_product_path
      end


  end

  def destroy
  end

  private

  def set_params
    params.require(:product).permit(:product_name,:price,:description,:color,:country,:expiration_date)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/home/index.html.erb
<div class="row justify-content-center">
<h1 class="mt-4">My shop</h1>
</div>
<div class="my-container">


<div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
  <ol class="carousel-indicators">
    <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
  </ol>
  <div class="carousel-inner">
    <div class="carousel-item active">
      <%= image_tag "shop1.jpg" ,class:"d-block w-100"%>
    </div>
    <div class="carousel-item">
      <%= image_tag "shop2.jpg" ,class:"d-block w-100" %>
    </div>
    <div class="carousel-item">
      <%= image_tag "shop3.jpg" ,class:"d-block w-100" %>
    </div>
  </div>
  <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>
</div>

app/views/layouts/_flash_messages.html.erb
 <% if notice %>

 <div class="alert alert-success alert-dismissible fade show " role="alert">
   <%= notice %>
   <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
 </div>
<% end %>

<% if alert %>

<div class="alert alert-danger alert-dismissible fade show " role="alert">
  <%= alert %>
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
     <span aria-hidden="true">&times;</span>
   </button>
</div>
<% end %>

app/views/layouts/_navigationbar.html.erb
<nav class="navbar navbar-expand-lg" style="background-color: #cd3bed;">
<a class="navbar-brand" href="#">Navbar</a>
<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
<span class="navbar-toggler-icon"></span>
</button>

<div class="collapse navbar-collapse" id="navbarSupportedContent">
<ul class="navbar-nav mr-auto">
  <li class="nav-item active">
    <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
  </li>
  <% if user_signed_in? %>
  <div class="btn-group dropright">
  <button type="button" class="btn btn-secondary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
    Product
  </button>
  <div class="dropdown-menu">
      <%= link_to 'View products' , products_path , class:"dropdown-item" %>
    <%= link_to 'Create product' , new_product_path , class:"dropdown-item" %>
  </div>
</div>
<%end%>

</ul>

<ul class="navbar-nav ml-auto">
<% if !user_signed_in? %>

  <li class="nav-item " >
    <%= link_to 'Sign up' ,new_user_registration_path,class:"btn btn-success " %>
  </li>

  <li class="nav-item ">
    <%= link_to 'Sign in' ,user_session_path,class:"btn btn-success " %>
  </li>


<% end %>

<% if user_signed_in?  %>

  <li class="nav-item" >
    <%= link_to 'Log out', destroy_user_session_path,method: :delete , class:"btn btn-light" %>
  </li>

<% end %>


</ul>

</div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ShopApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navigationbar' %>
    <%= render 'layouts/flash_messages' %>
    <div class="container">
      <%= yield %>
    </div>

  </body>
</html>

app/views/products/edit.html.erb
<div class="row justify-content-center">
<h1>Edit product</h1>

<div class="row">
  <%= simple_form_for @product do |f| %>

    <%= f.error_notification %>

    <%= f.input :product_name , class:"form-control shadow rounded" %>

    <%= f.input :price , class:"shadow rounded"%>

    <%= f.input :description , class:"shadow rounded" %>

    <%= f.input :color, as: :radio_buttons,
    collection: ['Red', 'Blue'] %>
  <%= f.input :country, collection: ['Albania', 'Italy','Greece','Germany','USA'], prompt: :translate %>

   <%= f.input :expiration_date %>

    <%= f.submit :submit ,class:"btn btn-primary"  %>

  <%end%>

</div>
</div>

app/views/products/index.html.erb
<h2>View products</h2>


<table class="table table-striped">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Product Name</th>
      <th scope="col">Price</th>
      <th scope="col">Descripion</th>
      <th scope="col">Color</th>
      <th scope="col">Country</th>
      <th scope="col">Expiration Date</th>
        <th scope="col">Action</th>
    </tr>
  </thead>
  <tbody>

    <% i=1 %>
    <% @products.each do | product | %>
    <tr>
      <th scope="row"><%= i %></th>
      <td><%= product.product_name %></td>
      <td><%= product.price %></td>
      <td><%= product.description %></td>
      <td><%= product.color %></td>
      <td><%= product.country %></td>
      <td><%= product.expiration_date %></td>
      <td><%= link_to 'Edit',edit_product_path(product),class:"btn btn-warning"%></td>
    </tr>
    <% i=i+1 %>
    <%end%>
  </tbody>
</table>

app/views/products/new.html.erb
<div class="row justify-content-center">
<h1>Create new product</h1>

<div class="row">
  
  <%= simple_form_for @product do |f| %>

    <%= f.error_notification %>

    <%= f.input :product_name ,:input_html => { :class => 'form-control shadow rounded', :placeholder => "name" } %>

    <%= f.input :price,:input_html => { :class => 'form-control shadow rounded', :placeholder => "price" } %>

    <%= f.input :description ,:input_html => { :class => 'form-control shadow rounded', :placeholder => "description" } %>

    <%= f.input :color, as: :radio_buttons,
    collection: ['Red', 'Blue'] %>

    <%= f.input :country, collection: ['Albania', 'Italy','Greece','Germany','USA'], prompt: :translate %>

     <%= f.input :expiration_date %>

    <%= f.submit :submit, class:"btn btn-primary"  %>

  <%end%>

</div>
</div>